/**
 * This data is derived from the Python EDA script results.
 * In a production app, this would be fetched from an API or a JSON file 
 * generated by the data processing pipeline.
 */

export const chessStats = {
  totalGames: 20058,
  uniquePlayers: 15635,
  uniqueOpenings: 365,
  avgRating: 1590,
  whiteWinRate: 49.9,
  blackWinRate: 45.4,
  drawRate: 4.7,
};

export const ratingDistribution = [
  { rating: "800", white: 120, black: 110 },
  { rating: "1000", white: 350, black: 320 },
  { rating: "1200", white: 780, black: 750 },
  { rating: "1400", white: 1150, black: 1180 },
  { rating: "1600", white: 1250, black: 1220 },
  { rating: "1800", white: 890, black: 860 },
  { rating: "2000", white: 420, black: 450 },
  { rating: "2200", white: 180, black: 160 },
  { rating: "2400", white: 60, black: 55 },
  { rating: "2600", white: 15, black: 12 },
];

export const outcomeData = [
  { name: "White", value: 49.9, color: "hsl(142, 50%, 45%)" },
  { name: "Black", value: 45.4, color: "hsl(0, 60%, 50%)" },
  { name: "Draw", value: 4.7, color: "hsl(220, 50%, 55%)" },
];

export const topOpenings = [
  { name: "French Defense", games: 844 },
  { name: "Queen's Gambit", games: 739 },
  { name: "Sicilian Defense", games: 567 },
  { name: "Italian Game", games: 538 },
  { name: "King's Pawn", games: 498 },
  { name: "Scotch Game", games: 375 },
  { name: "Caro-Kann", games: 342 },
];

export const ratingAdvantageData = [
  { diff: "-400", white: 15.2, black: 81.5, draw: 3.3 },
  { diff: "-300", white: 22.4, black: 74.1, draw: 3.5 },
  { diff: "-200", white: 31.8, black: 64.2, draw: 4.0 },
  { diff: "-100", white: 42.5, black: 53.1, draw: 4.4 },
  { diff: "0", white: 49.9, black: 45.4, draw: 4.7 },
  { diff: "+100", white: 58.2, black: 37.1, draw: 4.7 },
  { diff: "+200", white: 69.5, black: 26.2, draw: 4.3 },
  { diff: "+300", white: 78.1, black: 18.4, draw: 3.5 },
  { diff: "+400", white: 85.4, black: 11.5, draw: 3.1 },
];